# Generated by Django 3.2 on 2024-03-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_materials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.productmaterial'),
            preserve_default=False,
        ),
    ]
